version: "3.7"

services:
  mqtt:
    image: songpark-mqtt:latest
    build: .
    hostname: mosquitto
    container_name: mosquitto
    environment:
      - MQTT_USERNAME
      - MQTT_PASSWORD
    ports:
      - "30001:30001"
      - "30002:30002"
